### ISSUE TITLE
Assert bug

### ISSUE THREAD

**Issue by KJeff01** [maxsupermanhd/WMT#6]
Trying to use WMT on the Winteragony map (since commit 43ddc567594d949767147913f1c1c4fe34391a64) produces this error:

```
WMT: malloc.c:2392: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

**Comment by maxsupermanhd** [comment]
This is kinda strange bug. Actually im trying to fix it and im 90% shure in next commit it will work fine.
Possible solve: reload pc. (IDK it really helps)

**Comment by maxsupermanhd** [comment]
Try this again on current master. Maybe there is some changes...

**Comment by maxsupermanhd** [comment]
@KJeff01 Can you please attach this map so i can test this thing well. I sometimes cant reproduce this error...
![image](https://user-images.githubusercontent.com/20772987/72671325-76ed8780-3a59-11ea-922b-a88032a16ccd.png)

**Comment by KJeff01** [comment]
Just saw this now. The map works on latest master.

![2c-Winteragony](https://user-images.githubusercontent.com/22485442/72689236-fa988a00-3ad4-11ea-98e8-6679bbfce361.png)

[winteragony map.zip](https://github.com/maxsupermanhd/WMT/files/4083702/winteragony.map.zip)

**Comment by maxsupermanhd** [comment]
So this issue seems to be resolved or it's still appears? I've just ran WMT over all my downloaded maps and I can't spot any malloc errors.

**Comment by KJeff01** [comment]
I do not see this issue anymore. The last time I ran this program this particular map never worked so it's probably fixed.
